version: "3.7"

services:
  app:
    image: "tourizmsite"
    container_name: "tourizmsite_app"
    build: tourizmsite
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
        - variables/dev.env
    volumes:
      - ./website/:/app/

  postgres:
    image: postgres:12.0-alpine
    container_name: "website_postgres"
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - ./variables/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  