# Generated by Django 4.0.4 on 2022-06-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tourizmtype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourizmtype',
            name='category',
        ),
        migrations.AddField(
            model_name='tourplace',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категории'),
        ),
    ]
